### ISSUE TITLE
Need remove panic when run binary without parameter

### ISSUE THREAD

**Issue by mdshuai** [kubernetes-incubator/service-catalog#196]
When ```controller```, ```k8s-broker```, ```user-broker``` has no parameter, need output friendly tips not panic directly.
```
[root@dhcp-140-57 bin]# ./controller 
panic: Failed to create a kube config
:stat ./kubeconfig: no such file or directory


goroutine 1 [running]:
panic(0x123d920, 0xc420429e00)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.main()
	/data/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/catalog/service_controller.go:58 +0x642
[root@dhcp-140-57 bin]# ./k8s-broker 
panic: Need helm_binary specified

goroutine 1 [running]:
panic(0x6a31c0, 0xc42000d370)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.main()
	/data/src/github.com/kubernetes-incubator/service-catalog/contrib/broker/k8s/broker.go:58 +0x432
[root@dhcp-140-57 bin]# ./user-broker 
panic: Need helm_binary specified

goroutine 1 [running]:
panic(0x6a31c0, 0xc42000d370)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.main()
	/data/src/github.com/kubernetes-incubator/service-catalog/contrib/broker/k8s/broker.go:58 +0x432

```

**Comment by mdshuai** [comment]
```
[root@dhcp-140-57 bin]# ./service-catalog 
I1221 14:20:35.330341   13806 server.go:110] set up the server
I1221 14:20:35.330677   13806 server.go:117] set up serving options
E1221 14:20:35.330883   13806 server.go:125] set up etcd options, do you have `--etcd-servers localhost` set?
[root@dhcp-140-57 bin]# ./apiserver 
I1221 14:23:30.084653   13818 server.go:110] set up the server
I1221 14:23:30.084950   13818 server.go:117] set up serving options
E1221 14:23:30.084989   13818 server.go:125] set up etcd options, do you have `--etcd-servers localhost` set?
```
