### ISSUE TITLE
The UPS Broker Panics on Bind calls that happen before provision

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#584]
Here is a stack trace:

```console
ENG000656:svc-catalog-demo aaronschlesinger$ ks log -f ups-broker-ups-broker-791661979-11t0p
2017/03/20 17:07:31 http: panic serving 172.17.0.6:52338: runtime error: invalid memory address or nil pointer dereference
goroutine 40 [running]:
net/http.(*conn).serve.func1(0xc420074b80)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0x671460, 0xc420016040)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/kubernetes-incubator/service-catalog/contrib/pkg/broker/user_provided/controller.(*userProvidedController).Bind(0xc4200c8008, 0xc420074f1a, 0x24, 0xc420074f50, 0x24, 0xc420015b40, 0x40ff28, 0x30, 0x69aa40)
	/go/src/github.com/kubernetes-incubator/service-catalog/contrib/pkg/broker/user_provided/controller/controller.go:108 +0x5a
github.com/kubernetes-incubator/service-catalog/contrib/pkg/broker/server.(*server).bind(0xc4200ce1f0, 0x7def40, 0xc4201680d0, 0xc4200bfc20)
	/go/src/github.com/kubernetes-incubator/service-catalog/contrib/pkg/broker/server/server.go:146 +0x388
github.com/kubernetes-incubator/service-catalog/contrib/pkg/broker/server.(*server).(github.com/kubernetes-incubator/service-catalog/contrib/pkg/broker/server.bind)-fm(0x7def40, 0xc4201680d0, 0xc4200bfc20)
	/go/src/github.com/kubernetes-incubator/service-catalog/contrib/pkg/broker/server/server.go:49 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4200cef00, 0x7def40, 0xc4201680d0, 0xc4200bfc20)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/kubernetes-incubator/service-catalog/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4200cc0f0, 0x7def40, 0xc4201680d0, 0xc4200bfc20)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/github.com/gorilla/mux/mux.go:114 +0x10d
net/http.(*ServeMux).ServeHTTP(0x7f9f80, 0x7def40, 0xc4201680d0, 0xc420151950)
	/usr/local/go/src/net/http/server.go:2022 +0x7f
net/http.serverHandler.ServeHTTP(0xc4200e3100, 0x7def40, 0xc4201680d0, 0xc420151950)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420074b80, 0x7df500, 0xc420015480)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
2017/03/20 17:07:31 http: panic serving 172.17.0.6:52510: runtime error: invalid memory address or nil pointer dereference
goroutine 45 [running]:
net/http.(*conn).serve.func1(0xc420075100)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0x671460, 0xc420016040)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/kubernetes-incubator/service-catalog/contrib/pkg/broker/user_provided/controller.(*userProvidedController).Bind(0xc4200c8008, 0xc42007519a, 0x24, 0xc4200751d0, 0x24, 0xc420015d40, 0x40ff28, 0x30, 0x69aa40)
	/go/src/github.com/kubernetes-incubator/service-catalog/contrib/pkg/broker/user_provided/controller/controller.go:108 +0x5a
github.com/kubernetes-incubator/service-catalog/contrib/pkg/broker/server.(*server).bind(0xc4200ce1f0, 0x7def40, 0xc420168410, 0xc420196000)
	/go/src/github.com/kubernetes-incubator/service-catalog/contrib/pkg/broker/server/server.go:146 +0x388
github.com/kubernetes-incubator/service-catalog/contrib/pkg/broker/server.(*server).(github.com/kubernetes-incubator/service-catalog/contrib/pkg/broker/server.bind)-fm(0x7def40, 0xc420168410, 0xc420196000)
	/go/src/github.com/kubernetes-incubator/service-catalog/contrib/pkg/broker/server/server.go:49 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4200cef00, 0x7def40, 0xc420168410, 0xc420196000)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/kubernetes-incubator/service-catalog/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4200cc0f0, 0x7def40, 0xc420168410, 0xc420196000)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/github.com/gorilla/mux/mux.go:114 +0x10d
net/http.(*ServeMux).ServeHTTP(0x7f9f80, 0x7def40, 0xc420168410, 0xc4200bfe00)
	/usr/local/go/src/net/http/server.go:2022 +0x7f
net/http.serverHandler.ServeHTTP(0xc4200e3100, 0x7def40, 0xc420168410, 0xc4200bfe00)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420075100, 0x7df500, 0xc420015c40)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

**Comment by pmorie** [comment]
Interestingly, I have not had a problem with this, though I have been using the UPS broker extensively

**Comment by vaikas-google** [comment]
Could you add repro steps?

**Comment by arschles** [comment]
@vaikas-google I don't have reliable repro steps, because this looks like a race condition in the user provided broker

**Comment by arschles** [comment]
@vaikas-google actually one way to test this specific issue is to try to bind before provisioning against the UPS broker
